// <auto-generated />
using System;
using IT3045C_FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IT3045C_FinalProject.Migrations
{
    [DbContext(typeof(MemberInfo))]
    partial class MemberInfoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IT3045C_FinalProject.Models.Breakfast", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteBreakfastFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteBreakfastTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Breakfast");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteBreakfastFood = "Waffles",
                            FavoriteBreakfastTime = "10:00 AM",
                            FavoriteSide = "Bacon",
                            FullName = "Isabella Peters"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteBreakfastFood = "Waffles",
                            FavoriteBreakfastTime = "12:00 PM",
                            FavoriteSide = "Bacon",
                            FullName = "Logan Nemec"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteBreakfastFood = "French Toast",
                            FavoriteBreakfastTime = "6:00 AM",
                            FavoriteSide = "Coffee",
                            FullName = "Joseph Berger"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteBreakfastFood = "Bacon Egg & Cheese Biscuit",
                            FavoriteBreakfastTime = "8:00 AM",
                            FavoriteSide = "Toast",
                            FullName = "Tony Herrera"
                        },
                        new
                        {
                            Id = 5,
                            FavoriteBreakfastFood = "Egg Sandwich",
                            FavoriteBreakfastTime = "7:30 AM",
                            FavoriteSide = "Coffee",
                            FullName = "Taylor O'Black"
                        });
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Dinner", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteEntree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteRestaurant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteSide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dinner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteEntree = "Steak",
                            FavoriteRestaurant = "Alladins' Eatery",
                            FavoriteSide = "Mashed Potatoes",
                            FullName = "Isabella Peters"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteEntree = "Steak",
                            FavoriteRestaurant = "Swensons",
                            FavoriteSide = "Fried rice and noodles",
                            FullName = "Logan Nemec"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteEntree = "Pizza",
                            FavoriteRestaurant = "Dewey's",
                            FavoriteSide = "Fries",
                            FullName = "Joseph Berger"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteEntree = "Cheeseburger",
                            FavoriteRestaurant = "Culver's",
                            FavoriteSide = "Fries",
                            FullName = "Tony Herrera"
                        },
                        new
                        {
                            Id = 5,
                            FavoriteEntree = "Shephards Pie",
                            FavoriteRestaurant = "CheeseCake Factory",
                            FavoriteSide = "Roasted Potatoes",
                            FullName = "Taylor O'Black"
                        });
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Hobby", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteHobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowStarted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyStarted")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobby");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteHobby = "Hiking",
                            FullName = "Isabella Peters",
                            HowStarted = "My family would take me.",
                            WhyStarted = "To exercise"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteHobby = "Playing Video Games",
                            FullName = "Logan Nemec",
                            HowStarted = "Family and Friends",
                            WhyStarted = "For fun and good stress relief"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteHobby = "Extreme Deep Sea Diving",
                            FullName = "Joseph Berger",
                            HowStarted = "Became best friends with a local fisherman",
                            WhyStarted = "To gaze upon the amazing underwater sea"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteHobby = "Video Games",
                            FullName = "Tony Herrera",
                            HowStarted = "My brother made fun of me for being bad at them",
                            WhyStarted = "To beat my brother for bragging rights"
                        },
                        new
                        {
                            Id = 5,
                            FavoriteHobby = "Raising a Puppy",
                            FullName = "Taylor O'Black",
                            HowStarted = "Got a Shiba Inu with my partner",
                            WhyStarted = "I love puppies"
                        });
                });

            modelBuilder.Entity("IT3045C_FinalProject.Models.Member", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthdate = new DateTime(2001, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Isabella Peters",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            ID = 2,
                            Birthdate = new DateTime(2000, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Logan Nemec",
                            YearInProgram = "First Year"
                        },
                        new
                        {
                            ID = 3,
                            Birthdate = new DateTime(2000, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Joseph Berger",
                            YearInProgram = "Third Year"
                        },
                        new
                        {
                            ID = 4,
                            Birthdate = new DateTime(1999, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Tony Herrera",
                            YearInProgram = "Fourth Year"
                        },
                        new
                        {
                            ID = 5,
                            Birthdate = new DateTime(2000, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Taylor O'Black",
                            YearInProgram = "Third Year"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
